// =====COPYRIGHT=====
// Copyright 2007 - 2012 Service Repair Solutions, Inc.
// =====COPYRIGHT=====
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.Copyright.WebApplication.NifDBClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationFault", Namespace="http://schemas.datacontract.org/2004/07/Srs.WebServices.NifDB")]
    [System.SerializableAttribute()]
    public partial class ServiceOperationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InnerExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassName {
            get {
                return this.ClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassNameField, value) != true)) {
                    this.ClassNameField = value;
                    this.RaisePropertyChanged("ClassName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InnerExceptionMessage {
            get {
                return this.InnerExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionMessageField, value) != true)) {
                    this.InnerExceptionMessageField = value;
                    this.RaisePropertyChanged("InnerExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName {
            get {
                return this.MethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodNameField, value) != true)) {
                    this.MethodNameField = value;
                    this.RaisePropertyChanged("MethodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationName {
            get {
                return this.OperationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationNameField, value) != true)) {
                    this.OperationNameField = value;
                    this.RaisePropertyChanged("OperationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NifDBClient.IKeyBaseServiceV1")]
    public interface IKeyBaseServiceV1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeyBaseServiceV1/GetString", ReplyAction="http://tempuri.org/IKeyBaseServiceV1/GetStringResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebServices.Copyright.WebApplication.NifDBClient.ServiceOperationFault), Action="http://tempuri.org/IKeyBaseServiceV1/GetStringServiceOperationFaultFault", Name="ServiceOperationFault", Namespace="http://schemas.datacontract.org/2004/07/Srs.WebServices.NifDB")]
        string GetString(string sessionTokenId, string bucketNamespace, string password, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeyBaseServiceV1/Remove", ReplyAction="http://tempuri.org/IKeyBaseServiceV1/RemoveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebServices.Copyright.WebApplication.NifDBClient.ServiceOperationFault), Action="http://tempuri.org/IKeyBaseServiceV1/RemoveServiceOperationFaultFault", Name="ServiceOperationFault", Namespace="http://schemas.datacontract.org/2004/07/Srs.WebServices.NifDB")]
        bool Remove(string sessionTokenId, string bucketNamespace, string password, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeyBaseServiceV1/SaveString", ReplyAction="http://tempuri.org/IKeyBaseServiceV1/SaveStringResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebServices.Copyright.WebApplication.NifDBClient.ServiceOperationFault), Action="http://tempuri.org/IKeyBaseServiceV1/SaveStringServiceOperationFaultFault", Name="ServiceOperationFault", Namespace="http://schemas.datacontract.org/2004/07/Srs.WebServices.NifDB")]
        string SaveString(string sessionTokenId, string bucketNamespace, string password, string key, string stringValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeyBaseServiceV1/CreateBucket", ReplyAction="http://tempuri.org/IKeyBaseServiceV1/CreateBucketResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebServices.Copyright.WebApplication.NifDBClient.ServiceOperationFault), Action="http://tempuri.org/IKeyBaseServiceV1/CreateBucketServiceOperationFaultFault", Name="ServiceOperationFault", Namespace="http://schemas.datacontract.org/2004/07/Srs.WebServices.NifDB")]
        bool CreateBucket(string sessionTokenId, int productId, string bucketNamespace, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeyBaseServiceV1/GetBucketListByProduct", ReplyAction="http://tempuri.org/IKeyBaseServiceV1/GetBucketListByProductResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebServices.Copyright.WebApplication.NifDBClient.ServiceOperationFault), Action="http://tempuri.org/IKeyBaseServiceV1/GetBucketListByProductServiceOperationFaultF" +
            "ault", Name="ServiceOperationFault", Namespace="http://schemas.datacontract.org/2004/07/Srs.WebServices.NifDB")]
        string GetBucketListByProduct(string sessionTokenId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeyBaseServiceV1/DeleteBucket", ReplyAction="http://tempuri.org/IKeyBaseServiceV1/DeleteBucketResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebServices.Copyright.WebApplication.NifDBClient.ServiceOperationFault), Action="http://tempuri.org/IKeyBaseServiceV1/DeleteBucketServiceOperationFaultFault", Name="ServiceOperationFault", Namespace="http://schemas.datacontract.org/2004/07/Srs.WebServices.NifDB")]
        bool DeleteBucket(string sessionTokenId, int productId, string bucketNamespace);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKeyBaseServiceV1Channel : WebServices.Copyright.WebApplication.NifDBClient.IKeyBaseServiceV1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KeyBaseServiceV1Client : System.ServiceModel.ClientBase<WebServices.Copyright.WebApplication.NifDBClient.IKeyBaseServiceV1>, WebServices.Copyright.WebApplication.NifDBClient.IKeyBaseServiceV1 {
        
        public KeyBaseServiceV1Client() {
        }
        
        public KeyBaseServiceV1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KeyBaseServiceV1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyBaseServiceV1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyBaseServiceV1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetString(string sessionTokenId, string bucketNamespace, string password, string key) {
            return base.Channel.GetString(sessionTokenId, bucketNamespace, password, key);
        }
        
        public bool Remove(string sessionTokenId, string bucketNamespace, string password, string key) {
            return base.Channel.Remove(sessionTokenId, bucketNamespace, password, key);
        }
        
        public string SaveString(string sessionTokenId, string bucketNamespace, string password, string key, string stringValue) {
            return base.Channel.SaveString(sessionTokenId, bucketNamespace, password, key, stringValue);
        }
        
        public bool CreateBucket(string sessionTokenId, int productId, string bucketNamespace, string password) {
            return base.Channel.CreateBucket(sessionTokenId, productId, bucketNamespace, password);
        }
        
        public string GetBucketListByProduct(string sessionTokenId, int productId) {
            return base.Channel.GetBucketListByProduct(sessionTokenId, productId);
        }
        
        public bool DeleteBucket(string sessionTokenId, int productId, string bucketNamespace) {
            return base.Channel.DeleteBucket(sessionTokenId, productId, bucketNamespace);
        }
    }
}
